commit
JetMod/stellar-burgers pull request #1
Opened 2024-11-24 15:48 UTC by JetMod

2024-11-24 16:28 UTC, SergeyK2004 requested changes
Здравствуйте. 

Хочу обратить ваше внимание, что согласно задания, на проверку необходимо присылать ссылку на пулл реквест. не список файлов или коммитов, а именно пулл-реквест, в котором вы сдаете работу.

Посмотрите на гитхабе все комментарии к коду

Работа проделана огромная

Что сделано отлично:
Отлично сделана логика проверки, был ли пользователь на сайте, и показывать ли страницу с деталями, а не модальное окно. Весь заявленный функционал реализован. Здорово, что выделяется активная страница в главном меню. Бургер корректно собирается с возможностью менять ингредиенты местами.

Что нужно исправить:

* После оформления заказа, конструктор должен очищаться после получения ответа от сервера, а не после закрытия модального окна.
* https://disk.yandex.ru/d/4m0B4bWA1tv72A При открытии страницы "Лента заказов" выполняется огромное количество запросов для получения массива ингредиентов. Необходимо выполнить только один запрос за списком заказов.
* https://disk.yandex.ru/d/ZToVTe4Wc6OtLA  Заголовок формы некорректный. Отсутствует статус заказа. Сверьтесь с макетом. Проверьте так-же отображение заказа в отдельной странице.
* https://disk.yandex.ru/d/_0l0bBBZ-f3RzA Нужно центрировать контент на странице с деталями ингредиента.  Не отображается заголовок формы.
* https://disk.yandex.ru/d/6AmTPErFzK8XMg Не корректно выделяется активный пункт меню. Обратите внимание, что иконки в меню должны так-же изменять свое отображение в зависимости от активности пункта меню. Сверьтесь с макетом.
* https://disk.yandex.ru/d/q-Heh-BhSp-r0w В меню должно отображаться имя авторизованного пользователя.

Исправьте, пожалуйста, недочеты и работа будет принята. Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 
Напоминаю, что работа может быть принята только после исправления всех критических замечаний Нужно исправить.


Удачного рефакторинга кода.

2024-11-24 16:28 UTC, SergeyK2004 commented on src/components/app/app.tsx
> +  const background = location.state?.background;
Отлично

Отлично сделана логика проверки, был ли пользователь на сайте, и показывать ли страницу с деталями, а не модально окно

2024-11-24 16:28 UTC, SergeyK2004 commented on src/components/burger-constructor/burger-constructor.tsx
> +import { useSelector, useDispatch } from '../../services/store';
Отлично:
Хорошо, что используете типизированные хуки

2024-11-24 16:28 UTC, SergeyK2004 commented on src/components/ui/app-header/app-header.tsx
> +        <BurgerIcon type='primary' />
Надо исправить:
Иконки так-же меняют свое отображение у активного и не активного пункта меню.

2024-11-24 16:28 UTC, SergeyK2004 commented on src/components/ui/app-header/app-header.tsx
> +      <NavLink
Отлично:
Правильно, что используете NavLink

2024-11-24 16:28 UTC, SergeyK2004 commented on src/slices/burgerBuilderSlice.ts
> +        const id = nanoid();
**Отлично:**

Хорошо, что создание id вынесено в `prepare`

2024-11-25 18:53 UTC, JetMod commented
можете пожалуйста подсказать, у меня проблема с производительностью на странице Лента заказов, выполняется множество запросов для получения массива ингредиентов, не получается найти решение(

2024-11-26 06:47 UTC, SergeyK2004 approved these changes
Основные недочеты устранены. Но еще есть что можно улучшить:

* https://disk.yandex.ru/d/s9POzq6A8tw75A Обратите внимание на отображение пунктов меню. Выделяться должен только активный пункт.
* https://disk.yandex.ru/d/zt3TxUunjXg3pw Отсутствует заголовок.
* https://disk.yandex.ru/d/CYizDErEaUYBog Форма некорректно отображается. Сверьтесь с макетом.

Было бы очень здорово, проверять, как выглядит ваш сайт и сверять его отображение с макетом. Работу фронтендера в первую очередь оценивают по внешнему виду сайта.

Ваша работа принята. Желаю успехов в дальнейшем обучении.
Обратите внимание, что сейчас вам нужно смержить ветку review в main и после этого, при выполнении проектной работы следующего спринта создать новую ветку review, в которой вы будете покрывать приложение тестами. Старую ветку review после слияния можно удалить, чтобы она не мешала вам создавать новую.

2024-11-26 07:24 UTC, merged